version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU

environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
  GitHubToken:
    secure: ++Q00Aa+yzbi4oEn+fOuO2D2pb4NrFtQ12Hiq69arY1OgOIIUbth7nlImS9/wQRd
  AppVeyorToken:
    secure: 5mY0TVM+8MUtvl18rZ+eCuXoLMWgxJCpVRTUvry+mG4=
  NoWarn: ;1591;
   
xamarin:
  email: matthew.leibowitz@xamarin.com
  password:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  android: true
  ios: true

build_script:
 - cmd: dir "C:\Program Files (x86)\Android\"
 - cmd: dir "C:\Program Files (x86)\Android\android-sdk\tools\"
 - cmd: dir "C:\ProgramData\"
 - cmd: dir "C:\ProgramData\Android\"
 - cmd: dir "%USERPROFILE%\AppData\Local\"
 - cmd: dir "%USERPROFILE%\AppData\Local\Android\"
 - cmd: dir "%USERPROFILE%\AppData\Local\Android\android-sdk\tools\"
 - cmd: dir "C:\Users\appveyor\AppData\Local\Android\android-sdk\tools\"
# - ps: .\build.ps1 -Target Default-Windows -Configuration $Env:Configuration
  
artifacts:
 - path: output
 - path: output\*.nupkg
 - path: output\*.xam
